# Generated by Django 4.0.3 on 2022-05-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_avatar_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='avatares')),
                ('descripcion', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Nuevos',
        ),
        migrations.DeleteModel(
            name='Reciclar',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
