# Generated by Django 4.0.3 on 2022-05-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_blog_delete_nuevos_delete_reciclar_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
    ]
